  
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
 
FROM chaosbunny/build AS build
WORKDIR /src
RUN dotnet publish InMemoryIdentityApp -c Release -o /out --no-restore --no-build
RUN ls

FROM base AS final
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "InMemoryIdentityApp.dll"]