  
version: '3.4'

services:
  fluffybunny4:
    image: chaosbunny/app:latest
     
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7000:80
      - 7001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=5101
      - ApplicationInsights:InstrumentationKey=${ApplicationInsights_InstrumentationKey}
      - oidc:1:clientId=${oidc_1_clientId}
      - oidc:1:clientSecret=${oidc_1_clientSecret}
      - oidc:1:authority=${oidc_1_authority}
      - oidc:2:clientId=${oidc_2_clientId}
      - oidc:2:clientSecret=${oidc_2_clientSecret}
      - oidc:2:authority=${oidc_2_authority}


